services:
  backend:
    build: ./backend
    ports: 
      - 5050:5050
    depends_on:
      - database
      - ollama
    networks:
      - fluai_network

  ollama:
    build: ./ollama
    ports:
      - 11434:11434
    networks:
      - fluai_network

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fluaidb    
    volumes:
     - fluai_pg_data:/bitnami/postgresql
    networks:
      - fluai_network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - fluai_network

volumes:
  fluai_pg_data:

networks:
  fluai_network:
    driver: bridge