services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fluaidb    
    volumes:
     - fluai_pg_data:/bitnami/postgresql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
  
volumes:
  fluai_pg_data:
